"""
venn_shared_barcodes.py
=======================
V1–LGN barcode overlap: Venn diagrams + per-replicate bar chart (wider bars)
and a formatted text report.

Reads:  data/processed/invivo_metrics/Master_Corrected_Data.csv
Output: data/processed/invivo_metrics/Figure_Venn_SharedBC.pdf
        data/processed/invivo_metrics/Figure_Venn_SharedBC.svg
        data/processed/invivo_metrics/Venn_SharedBC_Report.txt
"""

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib_venn import venn2
import matplotlib.gridspec as gridspec
import numpy as np
from pathlib import Path

# ============================================================================
# 0. 路径 & 配置
# ============================================================================
SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT  = SCRIPT_DIR.parent if SCRIPT_DIR.name == 'notebook' else Path.cwd()

INPUT_CSV    = REPO_ROOT / "data" / "processed" / "invivo_metrics" / "Master_Corrected_Data.csv"
OUTPUT_DIR   = REPO_ROOT / "data" / "processed" / "invivo_metrics"
OUTPUT_PDF   = OUTPUT_DIR / "Figure_Venn_SharedBC.pdf"
OUTPUT_SVG   = OUTPUT_DIR / "Figure_Venn_SharedBC.svg"
OUTPUT_TXT   = OUTPUT_DIR / "Venn_SharedBC_Report.txt"

# 确保文字在 AI 中保持可编辑（不转轮廓）
plt.rcParams['pdf.fonttype']  = 42
plt.rcParams['ps.fonttype']   = 42
plt.rcParams['svg.fonttype']  = 'none'

CUSTOM_COLORS = {
    'HH + HdVRz':  '#1F77B4',
    'HH + Twister': '#D62728',
    'RzB + Twister': '#FF7F0E',
}
GROUPS = ['HH + HdVRz', 'HH + Twister', 'RzB + Twister']

# ============================================================================
# 1. 加载
# ============================================================================
print("正在读取数据 …")
if not INPUT_CSV.exists():
    raise FileNotFoundError(f"❌ {INPUT_CSV}")

df = pd.read_csv(INPUT_CSV)
barcode_col = 'RV_Barcode_Corrected' if 'RV_Barcode_Corrected' in df.columns else 'RV_Barcode'

# ============================================================================
# 2. 数据预处理
# ============================================================================
pooled_sets      = {}
rep_overlap_data = []

for group in GROUPS:
    group_df = df[df['Group'] == group]

    # --- pooled ---
    v1_bcs  = set(group_df[group_df['Brain_Region'].str.contains('V1', case=False, na=False)][barcode_col].unique())
    lgn_bcs = set(group_df[group_df['Brain_Region'].str.contains('LGN', case=False, na=False)][barcode_col].unique())
    pooled_sets[group] = (v1_bcs, lgn_bcs)

    # --- per replicate ---
    for rep in sorted(group_df['Replicate'].unique()):
        rep_df  = group_df[group_df['Replicate'] == rep]
        v1_rep  = set(rep_df[rep_df['Brain_Region'].str.contains('V1', case=False, na=False)][barcode_col].unique())
        lgn_rep = set(rep_df[rep_df['Brain_Region'].str.contains('LGN', case=False, na=False)][barcode_col].unique())
        rep_overlap_data.append({
            'Group': group,
            'Replicate': rep,
            'Shared_Barcodes': len(v1_rep & lgn_rep),
        })

bar_df = pd.DataFrame(rep_overlap_data)
bar_df['Group'] = pd.Categorical(bar_df['Group'], categories=GROUPS, ordered=True)

# ============================================================================
# 3. 文字报告
# ============================================================================
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

lines = []
sep_line = "=" * 65
lines.append(sep_line)
lines.append("  V1–LGN Trans-synaptic Shared Barcode Report")
lines.append(sep_line)
lines.append("\n[A]  Pooled Venn Set Sizes\n")
header_fmt = "  {:<22s}  {:>10s}  {:>10s}  {:>10s}"
lines.append(header_fmt.format("Group", "V1_Only", "LGN_Only", "Shared"))
lines.append("  " + "-" * 56)
for group in GROUPS:
    v1, lgn = pooled_sets[group]
    shared   = v1 & lgn
    lines.append(header_fmt.format(group, str(len(v1 - shared)), str(len(lgn - shared)), str(len(shared))))
lines.append("\n[B]  Per-Replicate Shared Barcode Counts\n")
rep_fmt = "  {:<22s}  {:>6s}  {:>10s}"
lines.append(rep_fmt.format("Group", "Rep", "Shared"))
lines.append("  " + "-" * 42)
for _, row in bar_df.iterrows():
    lines.append(rep_fmt.format(row['Group'], str(row['Replicate']), str(row['Shared_Barcodes'])))
lines.append("\n[C]  Group Summary (Mean ± SD)\n")
sum_fmt = "  {:<22s}  {:>10s}  {:>8s}  {:>10s}"
lines.append(sum_fmt.format("Group", "Mean", "SD", "N"))
lines.append("  " + "-" * 54)
for group in GROUPS:
    vals = bar_df[bar_df['Group'] == group]['Shared_Barcodes']
    lines.append(sum_fmt.format(group, f"{vals.mean():.1f}", f"{vals.std(ddof=1):.1f}", str(len(vals))))
lines.append("\n" + sep_line + "\n  Generated by venn_shared_barcodes.py\n" + sep_line)

with open(OUTPUT_TXT, 'w', encoding='utf-8') as f:
    f.write("\n".join(lines) + "\n")
print(f"💾 文字报告 → {OUTPUT_TXT}")

# ============================================================================
# 4. 画图 — Venn + Bar
# ============================================================================
fig = plt.figure(figsize=(24, 6))
gs  = gridspec.GridSpec(1, 4, width_ratios=[1, 1, 1, 1.2], wspace=0.2)

axes_venn = [fig.add_subplot(gs[0, i]) for i in range(3)]
ax_bar    = fig.add_subplot(gs[0, 3])

# ---- Venn 图 ----
for idx, group in enumerate(GROUPS):
    ax = axes_venn[idx]
    v1_bcs, lgn_bcs = pooled_sets[group]
    if len(v1_bcs) == 0:
        continue
    v = venn2([v1_bcs, lgn_bcs],
              set_labels=('V1\n(Starter)', 'LGN\n(Target)'),
              set_colors=(CUSTOM_COLORS[group], '#A9A9A9'),
              alpha=0.7, ax=ax)
    if v:
        for lid in ('10', '01'):
            lbl = v.get_label_by_id(lid)
            if lbl:
                lbl.set_fontsize(13)
        lbl_11 = v.get_label_by_id('11')
        if lbl_11:
            lbl_11.set_fontsize(16)
            lbl_11.set_fontweight('bold')
        for text in v.set_labels:
            if text:
                text.set_fontsize(15)
                text.set_fontweight('bold')
    ax.set_title(group, fontsize=18, fontweight='bold', pad=10)

# ---- Bar chart: matplotlib bar + scatter (wider bars) ----
stats = bar_df.groupby('Group', observed=True)['Shared_Barcodes'].agg(['mean', 'std'])
stats = stats.reindex(GROUPS)

x     = np.arange(len(GROUPS))
width = 0.55
colors = [CUSTOM_COLORS[g] for g in GROUPS]

bars = ax_bar.bar(x, stats['mean'], width, yerr=stats['std'],
                  color=colors, edgecolor='black', linewidth=1.5,
                  capsize=8, zorder=2)

# scatter per replicate — centred on each bar
for i, group in enumerate(GROUPS):
    rep_vals = bar_df[bar_df['Group'] == group]['Shared_Barcodes'].values
    jitter = np.random.default_rng(42).uniform(-0.08, 0.08, len(rep_vals))
    ax_bar.scatter(np.full_like(rep_vals, x[i]) + jitter, rep_vals,
                   color='#222222', s=80, edgecolor='white', linewidth=1.2,
                   zorder=3)

ax_bar.set_xticks(x)
ax_bar.set_xticklabels(GROUPS, rotation=15, ha='right', fontsize=14, fontweight='bold')
for tick in ax_bar.get_xticklabels():
    tick.set_color(CUSTOM_COLORS.get(tick.get_text(), 'black'))

ax_bar.set_title('Absolute Shared Barcodes\n(Per Biological Replicate)',
                 fontsize=18, fontweight='bold', pad=15)
ax_bar.set_ylabel('Number of Shared RV-Barcodes', fontsize=14, fontweight='bold')
ax_bar.spines['top'].set_visible(False)
ax_bar.spines['right'].set_visible(False)
ax_bar.yaxis.grid(True, linestyle=':', alpha=0.4)

# ============================================================================
# 5. 保存
# ============================================================================
fig.suptitle('Trans-synaptic Connection Fidelity & Absolute Bandwidth',
             fontsize=24, fontweight='bold', y=1.08)
plt.subplots_adjust(top=0.85, bottom=0.15)

plt.savefig(OUTPUT_PDF, format='pdf', dpi=300, bbox_inches='tight')
plt.savefig(OUTPUT_SVG, format='svg', dpi=300, bbox_inches='tight')
plt.close()

print(f"🎉 图片 → {OUTPUT_PDF}")
